services:
  donejournal:
    image: ghcr.io/sxwebdev/donejournal:latest
    command: ["start", "-c", "./config.yaml"]
    container_name: donejournal
    restart: unless-stopped
    volumes:
      - ./config.yaml:/app/config.yaml
